# Generated by Django 5.2.4 on 2025-08-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='frontend/static/uploads/'),
        ),
    ]
